import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { MainNav } from "@/components/main-navbar"
import { TopBar } from '@/components/top-bar';
import { createClient } from '@/utils/supabase/server'
import LandingPage from '@/components/landing-page';
import apiClient from '@/lib/api';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: userData, error: userError } = await supabase.auth.getUser();

  if (userError || !userData?.user) {
    return (
      <html lang="en">
        <body>
          <LandingPage />
        </body>
      </html>
    );
  }

  const user = await apiClient.users.getUser(userData.user.id);

  // const { data: sessionData } = await supabase.auth.getSession();
  // const accessToken = sessionData.session?.access_token;
  // const res = await fetch(
  //   `${process.env.NEXT_PUBLIC_API_URL}/users/${userData.user.id}`,
  //   {
  //     headers: {
  //       "Content-Type": "application/json",
  //       ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
  //     },
  //     // Optionally add cache: 'no-store' if you don't want caching
  //     cache: "no-store",
  //   }
  // );


  // // if (!res.ok) {
  // //   console.error("Error fetching user from backend API");
  // //   throw new Error("Failed to fetch user");
  // // }

  // const user = await res.json();

  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex min-h-screen flex-col w-full">
            <TopBar user={user} />
            <div className="flex-1 flex">
              <MainNav />
              {children}
            </div>
          </div>

        </SidebarProvider>
      </body>
    </html >
  );
}


// {/* Wrap sidebar and content in a flex container */}
// <div className="flex">
//   {/* Sidebar on the left */}
//   <MainNav />

//   {/* Main content on the right */}
//   <main className="flex-1">
//     {children}
//   </main>
// </div>