import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { MainNav } from "@/components/main-navbar"
import { TopBar } from '@/components/top-bar';
import { createClient } from '@/utils/supabase/server'
import LandingPage from '@/components/landing-page';
import server_api from "@/lib/api/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: userData, error: userError } = await supabase.auth.getUser();

  if (userError || !userData?.user) {
    return (
      <html lang="en">
        <body>
          <LandingPage />
        </body>
      </html>
    );
  }

  const user = await server_api.users.getUser(userData.user.id);

  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="flex min-h-screen flex-col w-full">
            <TopBar user={user} />
            <div className="flex-1 flex">
              <MainNav />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html >
  );
}